server:
  port: 1234
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astrodb?createDatabaseIfNotExist=true
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: deepak.kumar.rd2013@gmail.com
    password: ouyb tauv udkd cssf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    defaultModelsExpandDepth: -1
    docExpansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    enabled: true
  model-and-view-allowed: false
  override-with-generic-response: false
  auto-tag-classes: false
otp:
  expiry-minutes: 5

textlocal:
  api-key: "YOUR_TEXTLOCAL_API_KEY"
  sender: "TXTLCL"

twofactor:
  enabled: true
  base-url: "https://2factor.in"
  api-key: "210c5d7a-0d79-11ec-a13b-0200cd936042"
  otp-template-name: "AstroAdhyaay"

resend:
  api-key: "re_CCseECjB_Bv36rHa5RYTMWJwyjnQtd8j6"
  from-email: "onboarding@resend.dev"

app:
  mail:
    from: "deepak.kumar.rd2013@gmail.com"

razorpay:
  key-id: "rzp_live_SGnLtGTl5vgLLC"
  key-secret: "snhHxD0UbGEx6fBhCZ9N9rHo"

free-astrology:
  base-url: "https://json.freeastrologyapi.com"
  api-key: "64mIJQUBn47P6znPRzWa52hMvu6fPKuy7DJycxS6"

fcm:
  enabled: true
  project-id: ${FCM_PROJECT_ID:}
  service-account-file: ${FCM_SERVICE_ACCOUNT_FILE:classpath:firebase-service-account.json}
  service-account-json: ${FCM_SERVICE_ACCOUNT_JSON:}
  service-account-base64: ${FCM_SERVICE_ACCOUNT_BASE64:}

agora:
  app-id: ${AGORA_APP_ID:cbe31f2b8684484a92cdcb6b81ca8ab6}
  app-certificate: ${AGORA_APP_CERTIFICATE:}
  token-expire-seconds: ${AGORA_TOKEN_EXPIRE_SECONDS:3600}
