server:
  port: 1234
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astrodb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    defaultModelsExpandDepth: -1
    docExpansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    enabled: true
  model-and-view-allowed: false
  override-with-generic-response: false
  auto-tag-classes: false
otp:
  expiry-minutes: 5

textlocal:
  api-key: "YOUR_TEXTLOCAL_API_KEY"
  sender: "TXTLCL"

sendgrid:
  api-key: "YOUR_SENDGRID_API_KEY"
  from-email: "noreply@yourdomain.com"

razorpay:
  key-id: "YOUR_RAZORPAY_KEY"
  key-secret: "YOUR_RAZORPAY_SECRET"